Repository ThibautHH/MyPandoc, pull requests merged in 2024-04, with the labels that each got.

#2 ci(dependabot) Add dependabot for Github Actions
  .github/dependabot.yml
Labels: automation

#4 Format
  .gitignore
  MyPandoc.cabal
  app/Main.hs
  src/Conf.hs
  src/ConfUtils.hs
  src/Decode.hs
  src/Encode.hs
Labels: enhancement

#5 feat(core) Add Document data types
  app/Main.hs
  src/Decode.hs
  src/Encode.hs
  src/Lib.hs
Labels: enhancement

#7 fix(conf) Fix Conf.confParser optional arguments
  src/Conf.hs
Labels: bug

#10 fix(decoder) Fix Header decoding
  src/Decode.hs
Labels: bug

#9 feat(core) Handle output file argument
  app/Main.hs
Labels: enhancement
